/** Wikimedia Commons (CC BY-SA). Generated by scripts/download-isaret-png.js */
import type { ImageSourcePropType } from "react-native";

export const ISARET_IMAGES: Record<string, ImageSourcePropType> = {
  "is-15": require("../../assets/isaretler/is-15.png"),
};

export const ISARET_IMAGE_ATTRIBUTION = "Levha görselleri: Wikimedia Commons (CC BY-SA) — Karayolları Genel Müdürlüğü standart levhaları.";